services:
  db:
    # Should be the same as in `../contenttree-backend/compose.yaml`:
    image: dhi.io/postgres:18.4-alpine3.23@sha256:b18a3537d1273920565544b084a80918be565cadaf381112769b4bcf760b7555
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_username
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: contenttree
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - db_username
      - db_password
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "/bin/bash", "-c", "pg_isready -U $(cat $${POSTGRES_USER_FILE}) -d contenttree" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_interval: 3s
      start_period: 20s

  backend:
    depends_on:
      db:
        condition: service_healthy
    image: ${BACKEND_IMAGE:-contenttree-backend:latest}
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/contenttree
      - SPRING_CONFIG_IMPORT=file:/run/secrets/backend_config[.properties]
      - APP_CORS_ALLOWED_ORIGINS=http://localhost:8080,http://localhost:8084
      - THC_PATH=/actuator/health/readiness
      - THC_PORT=8082
    secrets:
      - backend_config
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "/workspace/health-check" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_interval: 3s
      start_period: 30s

  frontend-angular:
    image: ${FRONTEND_ANGULAR_IMAGE:-contenttree-frontend-angular:latest}
    ports:
      - "8080:8080"
    environment:
      - API_BASE_URL=http://localhost:8081
    networks:
      - app-network
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://frontend-angular:8080/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_interval: 3s
      start_period: 10s

  frontend-nextjs:
    image: ${FRONTEND_NEXTJS_IMAGE:-contenttree-frontend-nextjs:latest}
    ports:
      - "8084:3000"
    environment:
      - API_BASE_URL=http://localhost:8081
    networks:
      - app-network
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test: [ "CMD", "node", "healthcheck.mjs" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_interval: 3s
      start_period: 10s

volumes:
  db-data:
    driver: local

networks:
  app-network:
    driver: bridge

secrets:
  db_username:
    file: etc/db/username
  db_password:
    file: etc/db/password
  backend_config:
    file: etc/backend/application.properties
