services:
  db:
    # Should be the same as in `../contenttree-backend/compose.yaml`:
    image: dhi.io/postgres:18.4-alpine3.23@sha256:b18a3537d1273920565544b084a80918be565cadaf381112769b4bcf760b7555
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prodsecret
      POSTGRES_DB: contenttree
    networks:
      - db-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "contenttree" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_interval: 3s
      start_period: 20s

  backend:
    depends_on:
      db:
        condition: service_healthy
    image: ${BACKEND_IMAGE:-contenttree-backend:latest}
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/contenttree
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=prodsecret
      - APP_CORS_ALLOWED_ORIGINS=http://localhost:8080
      - THC_PATH=/actuator/health/readiness
      - THC_PORT=8082
    networks:
      - db-network
    healthcheck:
      test: [ "CMD", "/workspace/health-check" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_interval: 3s
      start_period: 30s

  frontend:
    image: ${FRONTEND_IMAGE:-contenttree-frontend:latest}
    ports:
      - "8080:8080"
    environment:
      - API_BASE_URL=http://localhost:8081
    networks:
      - db-network
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://frontend:8080/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_interval: 3s
      start_period: 10s

volumes:
  db-data:
    driver: local

networks:
  db-network:
    driver: bridge
