sonar.projectKey=contenttree-frontend
sonar.organization=rkrisztian
sonar.projectName=contenttree-frontend
sonar.sources=src
sonar.tests=src
sonar.javascript.lcov.reportPaths=coverage/lcov.info, coverage-ct/lcov.info
sonar.exclusions=**/*.spec.ts, src/test-utils/**/*.ts
sonar.test.inclusions=src/**/*.spec.ts, src/test-utils/**/*.ts
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=src/app/api/schema.d.ts, src/environments/**/*.ts
