sonar.projectKey=contenttree-frontend
sonar.organization=rkrisztian
sonar.projectName=contenttree-frontend
sonar.sources=src
sonar.tests=src
sonar.javascript.lcov.reportPaths=coverage/contenttree/lcov.info
sonar.exclusions=**/*.spec.ts
sonar.test.inclusions=src/**/*.spec.ts
sonar.sourceEncoding=UTF-8
