services:
  db:
    # see `.env` file
    image: ${POSTGRES_IMAGE}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: contenttree
    networks:
      - db-network

  # Optional: A DB manager tool you can use if you don't have IntelliJ IDEA Ultimate subscription
  dbgate:
    profiles: [ debug ]
    image: dbgate/dbgate:7.2.5-alpine@sha256:4d61f9a89f1a39806c25593f0bf160626767456e74e098d06fbf1d6468c4cc18
    ports:
      - "5433:3000"
    environment:
      CONNECTIONS: pg

      LABEL_pg: content-tree-db
      SERVER_pg: db
      USER_pg: postgres
      PASSWORD_pg: secret
      PORT_pg: 5432
      ENGINE_pg: postgres@dbgate-plugin-postgres
    networks:
      - db-network

volumes:
  db-data:
    driver:
      local

networks:
  db-network:
    driver: bridge
