sonar.projectKey=contenttree-frontend-nextjs
sonar.organization=rkrisztian
sonar.projectName=contenttree-frontend-nextjs
sonar.sources=src, Dockerfile
sonar.tests=src
sonar.javascript.lcov.reportPaths=coverage/lcov.info, coverage-ct/lcov.info
sonar.exclusions=src/app/_lib/api/types/**, **/*.spec.ts, **/*.spec.tsx, src/test-utils/**/*.ts, src/test-utils/**/*.tsx
sonar.test.inclusions=src/**/*.spec.ts, src/**/*.spec.tsx, src/test-utils/**/*.ts, src/test-utils/**/*.tsx
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=src/proxy.ts, src/app/layout.tsx

sonar.issue.ignore.multicriteria=e1,e2
# Using both version tag and digest is helpful for Dependabot upgrades.
# See https://community.sonarsource.com/t/docker-s8431-makes-dependabot-upgrades-harder-to-read-and-limits-its-features/183693
sonar.issue.ignore.multicriteria.e1.ruleKey=docker:S8431
sonar.issue.ignore.multicriteria.e1.resourceKey=Dockerfile
# useMemo is rarely needed now with React 18+.
# See https://community.sonarsource.com/t/deprecate-rule-typescript-s6481-unstable-context-value-object-now-that-react-has-a-compiler/138994
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S6481
sonar.issue.ignore.multicriteria.e2.resourceKey=src/**/*.tsx
