name: CI Pipeline - Backend

on:
  workflow_call:

jobs:
  build:
    name: Build
    defaults:
      run:
        working-directory: contenttree-backend
    runs-on: ubuntu-latest
    steps:
      - name: (Harden Runner)
        uses: step-security/harden-runner@v2.20.0  # Immutable
        with:
          egress-policy: audit
          disable-telemetry: true

      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: (Set up JDK)
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961  # v5.7.0
        with:
          java-version-file: 'contenttree-backend/.java-version'
          # For consistency with the JVM choice in the Docker build
          distribution: 'zulu'

      - name: (Cache .gradle)
        uses: burrunan/gradle-cache-action@4b67497abd37a511d6c1dc6299bdd84ff39f7bf5  # v3.0.2
        with:
          read-only: ${{ github.ref != 'refs/heads/main' }}
          build-root-directory: contenttree-backend

      - name: (Log in to Docker Hardened Images distribution registry)
        uses: docker/login-action@v4.6.0  # Immutable
        with:
          registry: dhi.io
          # If username is sensitive for you, use a secret variable instead.
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: (Set Gradle Logging Level to Info)
        if: ${{ runner.debug == '1' }}
        run: echo 'GRADLE_OPTS=-Dorg.gradle.logging.level=info' >> $GITHUB_ENV

      - name: Build Backend
        run: ./gradlew build

      - name: Generate and submit dependency graph
        if: ${{ (github.event_name != 'pull_request') && !cancelled()  }}
        uses: gradle/actions/dependency-submission@9c971963bec38e04b3d30dcc455b5382be2fdbfb  # v6.3.0
        with:
          dependency-graph: generate-and-submit
          build-root-directory: contenttree-backend

      - name: SonarQubeCloud Scan
        if: ${{ ((github.event_name != 'pull_request') || (github.event.pull_request.user.login != 'dependabot[bot]')) && !cancelled() }}
        run: ./gradlew sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: (Log in to GitHub Container Registry)
        if: ${{ (github.event_name != 'pull_request') && success() }}
        uses: docker/login-action@v4.6.0  # Immutable
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and Push Docker Image
        run: ./gradlew bootBuildImage -PpublishImage=${{ github.event_name != 'pull_request' }}
        env:
          GHCR_USER: ${{ github.repository_owner }}
