name: CI Build - Backend

on:
  workflow_call:

jobs:
  build:
    name: Build
    defaults:
      run:
        working-directory: contenttree-backend
    runs-on: ubuntu-latest
    steps:
      - name: (Harden Runner)
        uses: step-security/harden-runner@v2.19.4  # Immutable
        with:
          egress-policy: audit
          disable-telemetry: true

      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: (Set up JDK)
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654  # v5.2.0
        with:
          java-version-file: 'contenttree-backend/.java-version'
          # For consistency with the JVM choice in the Docker build
          distribution: 'zulu'

      - name: (Cache .gradle)
        uses: burrunan/gradle-cache-action@4b67497abd37a511d6c1dc6299bdd84ff39f7bf5  # v3.0.2
        with:
          read-only: ${{ github.ref != 'refs/heads/main' }}
          build-root-directory: contenttree-backend

      - name: (Log in to Docker Hardened Images distribution registry)
        uses: docker/login-action@v4.2.0  # Immutable
        with:
          registry: dhi.io
          # If username is sensitive for you, use a secret variable instead.
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend
        run: ./gradlew build

      - name: Build Docker Image
        run: ./gradlew bootBuildImage

      - name: Generate and submit dependency graph
        if: ${{ (github.event_name != 'pull_request') && !cancelled()  }}
        uses: gradle/actions/dependency-submission@3f131e8634966bd73d06cc69884922b02e6faf92  # v6.2.0
        with:
          dependency-graph: generate-and-submit
          build-root-directory: contenttree-backend

      - name: SonarQubeCloud Scan
        run: ./gradlew sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
