name: CI Pipeline - Dependency Review

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: (Harden Runner)
        uses: step-security/harden-runner@v2.19.4  # Immutable
        with:
          egress-policy: audit
          disable-telemetry: true

      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0

      - name: Dependency Review
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294  # v5.0.0
        with:
          show-patched-versions: true
          retry-on-snapshot-warnings: true
          retry-on-snapshot-warnings-timeout: 300
