name: CI Pipeline - Frontend (Angular)

on:
  workflow_call:

jobs:
  build:
    name: Build
    defaults:
      run:
        working-directory: contenttree-frontend-angular
    runs-on: ubuntu-latest
    steps:
      - name: (Harden Runner)
        uses: step-security/harden-runner@v2.20.1  # Immutable
        with:
          egress-policy: block
          allowed-endpoints: >
            *.gvt1.com:443
            accounts.google.com:443
            analysis-sensorcache-eu-central-1-prod.s3.eu-central-1.amazonaws.com:443
            android.clients.google.com:443
            api.github.com:443
            api.sonarcloud.io:443
            auth.docker.io:443
            binaries.sonarsource.com:443
            cdn.playwright.dev:443
            clients2.google.com:80
            content-autofill.googleapis.com:443
            dhi.io:443
            dna-visualization-scannerdata-eu-central-1-prod.s3.eu-central-1.amazonaws.com:443
            ghcr.io:443
            github.com:443
            keyserver.ubuntu.com:443
            mtalk.google.com:5228
            playwright.download.prss.microsoft.com:443
            production.cloudfront.docker.com:443
            registry-1.docker.io:443
            registry.npmjs.org:443
            release-assets.githubusercontent.com:443
            safebrowsingohttpgateway.googleapis.com:443
            scanner.sonarcloud.io:443
            sonarcloud.io:443
            storage.googleapis.com:443
            update.googleapis.com:443
            update.googleapis.com:80
            www.google.com:443
            www.gstatic.com:443
          disable-telemetry: true

      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: (Set up Node.js)
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version-file: contenttree-frontend-angular/.node_version
          cache: 'npm'
          cache-dependency-path: contenttree-frontend-angular/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build

      - name: Run Lint
        run: npm run lint

      # ESLint does not support multiple reporter formats in one go.
      # See: https://github.com/eslint/eslint/issues/19990
      - name: (Generate ESLint report for Sonar)
        if: ${{ ((github.event_name != 'pull_request') || (github.event.pull_request.user.login != 'dependabot[bot]')) && !cancelled() }}
        run: npm run lint:sonar

      - name: Analyze Imports for Cyclic Dependencies
        run: npm run lint:dpdm

      - name: Run Formatting Checks
        run: npm run format:check

      - name: Run Unit Tests
        run: npm test

      - name: Install Playwright Browser (Chromium)
        run: npm run install:chromium

      - name: Run Component Tests
        run: npm run test:ct

      - name: (Log in to Docker Hardened Images distribution registry)
        uses: docker/login-action@v4.6.0  # Immutable
        with:
          registry: dhi.io
          # If username is sensitive for you, use a secret variable instead.
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: (Set up Docker Buildx)
        uses: docker/setup-buildx-action@v4.2.0  # Immutable

      - name: (Get Project Version)
        run: echo "PROJECT_VERSION=$(cat .version)" >> $GITHUB_ENV
        working-directory: .

      - name: SonarQube Scan
        if: ${{ ((github.event_name != 'pull_request') || (github.event.pull_request.user.login != 'dependabot[bot]')) && !cancelled() }}
        uses: SonarSource/sonarqube-scan-action@v8.2.1  # Immutable
        with:
          projectBaseDir: contenttree-frontend-angular
          args: >
            -Dsonar.projectVersion=${{ env.PROJECT_VERSION }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: (Log in to GitHub Container Registry)
        if: ${{ (github.event_name != 'pull_request') && success() }}
        uses: docker/login-action@v4.6.0  # Immutable
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v7.3.0  # Immutable
        with:
          context: contenttree-frontend-angular
          tags: "ghcr.io/${{ github.repository_owner }}/contenttree-frontend-angular:${{ env.PROJECT_VERSION }}-snapshot"
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
