name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: true
        default: 'Manual pipeline run'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changes:
    name: Detect Changes
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend-angular: ${{ steps.filter.outputs.frontend-angular }}
      frontend-nextjs: ${{ steps.filter.outputs.frontend-nextjs }}
      deploy: ${{ steps.filter.outputs.deploy }}
    steps:
      - name: (Harden Runner)
        uses: step-security/harden-runner@v2.20.1  # Immutable
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
          disable-telemetry: true

      - name: Check out code
        if: ${{ (github.event_name != 'pull_request') && !cancelled() }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706  # v4.0.2
        id: filter
        with:
          filters: |
            backend:
              - 'contenttree-backend/**'
              - '.github/workflows/ci.yml'
              - '.github/workflows/ci-backend.yml'
            frontend-angular:
              - 'contenttree-frontend-angular/**'
              - '.github/workflows/ci.yml'
              - '.github/workflows/ci-frontend-angular.yml'
            frontend-nextjs:
              - 'contenttree-frontend-nextjs/**'
              - '.github/workflows/ci.yml'
              - '.github/workflows/ci-frontend-nextjs.yml'
            deploy:
              - 'contenttree-deploy/**'
              - '.github/workflows/ci.yml'
              - '.github/workflows/ci-deploy.yml'

  backend:
    name: Backend
    needs: changes
    if: ${{ ((needs.changes.outputs.backend == 'true') || (github.event_name == 'workflow_dispatch')) && !cancelled() }}
    permissions:
      contents: write  # Needed by the `dependency-submission` action.
      packages: write  # Needed for publishing docker images to GHCR.
    uses: ./.github/workflows/ci-backend.yml
    secrets: inherit

  frontend-angular:
    name: Frontend (Angular)
    needs: changes
    if: ${{ ((needs.changes.outputs.frontend-angular == 'true') || (github.event_name == 'workflow_dispatch')) && !cancelled() }}
    permissions:
      contents: read
      packages: write  # Needed for publishing docker images to GHCR.
    uses: ./.github/workflows/ci-frontend-angular.yml
    secrets: inherit

  frontend-nextjs:
    name: Frontend (Next.js)
    needs: changes
    if: ${{ ((needs.changes.outputs.frontend-nextjs == 'true') || (github.event_name == 'workflow_dispatch')) && !cancelled() }}
    permissions:
      contents: read
      packages: write  # Needed for publishing docker images to GHCR.
    uses: ./.github/workflows/ci-frontend-nextjs.yml
    secrets: inherit

  deploy-ci:
    name: Deploy (CI)
    needs: changes
    if: ${{ ((needs.changes.outputs.deploy == 'true') || (github.event_name == 'workflow_dispatch')) && !cancelled() }}
    permissions:
      contents: read
    uses: ./.github/workflows/ci-deploy.yml
    secrets: inherit
