name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: (Harden Runner)
        uses: step-security/harden-runner@v2.19.4  # Immutable
        with:
          egress-policy: audit
          disable-telemetry: true

      - name: Check out code
        if: ${{ (github.event_name != 'pull_request') && !cancelled() }}
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d  # v4.0.1
        id: filter
        with:
          filters: |
            backend:
              - 'contenttree-backend/**'
              - '.github/workflows/ci.yml'
            frontend:
              - 'contenttree-frontend/**'
              - '.github/workflows/ci.yml'

  build-backend:
    name: Build Backend (Spring Boot)
    needs: changes
    if: ${{ (needs.changes.outputs.backend == 'true') && !cancelled()  }}
    defaults:
      run:
        working-directory: contenttree-backend
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed by the `dependency-submission` action
    steps:
      - name: (Harden Runner)
        uses: step-security/harden-runner@v2.19.4  # Immutable
        with:
          egress-policy: audit
          disable-telemetry: true

      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: (Set up JDK)
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654  # v5.2.0
        with:
          java-version-file: 'contenttree-backend/.java-version'
          # For consistency with the JVM choice in the Docker build
          distribution: 'zulu'

      - name: (Cache .gradle)
        uses: burrunan/gradle-cache-action@4b67497abd37a511d6c1dc6299bdd84ff39f7bf5  # v3.0.2
        with:
          read-only: ${{ github.ref != 'refs/heads/main' }}
          build-root-directory: contenttree-backend

      - name: (Log in to Docker Hardened Images distribution registry)
        uses: docker/login-action@v4.2.0  # Immutable
        with:
          registry: dhi.io
          # If username is sensitive for you, use a secret variable instead.
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend
        run: ./gradlew build

      - name: Build Docker Image
        run: ./gradlew bootBuildImage

      - name: Generate and submit dependency graph
        if: ${{ (github.event_name != 'pull_request') && !cancelled()  }}
        uses: gradle/actions/dependency-submission@3f131e8634966bd73d06cc69884922b02e6faf92  # v6.2.0
        with:
          dependency-graph: generate-and-submit
          build-root-directory: contenttree-backend

      - name: SonarQubeCloud Scan
        run: ./gradlew sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-frontend:
    name: Build Frontend (Angular)
    needs: changes
    if: ${{ (needs.changes.outputs.frontend == 'true') && !cancelled()  }}
    defaults:
      run:
        working-directory: contenttree-frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: (Harden Runner)
        uses: step-security/harden-runner@v2.19.4  # Immutable
        with:
          egress-policy: audit

      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: (Set up Node.js)
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
        with:
          node-version-file: contenttree-frontend/.node_version
          cache: 'npm'
          cache-dependency-path: contenttree-frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build

      - name: Run Lint
        run: npm run lint

      # ESLint does not support multiple reporter formats in one go.
      # See: https://github.com/eslint/eslint/issues/19990
      - name: (Generate ESLint report for Sonar)
        run: npm run lint:sonar

      - name: Run Unit Tests
        run: npm test

      - name: Install Playwright Browser
        run: npx playwright install chromium

      - name: Run Component Tests
        run: npm run test:ct

      - name: (Log in to Docker Hardened Images distribution registry)
        uses: docker/login-action@v4.2.0  # Immutable
        with:
          registry: dhi.io
          # If username is sensitive for you, use a secret variable instead.
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: (Set up Docker Buildx)
        uses: docker/setup-buildx-action@v4.1.0  # Immutable

      - name: Build Docker Image
        uses: docker/build-push-action@v7.2.0  # Immutable
        with:
          context: contenttree-frontend
          tags: contenttree-frontend:latest
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Project version is not picked up automatically.
      # See: https://github.com/bellingard/sonar-scanner-npm/issues/75
      - name: (Get Frontend Version for SonarQube Scan)
        id: get-frontend-version
        run: echo "version=$(node -pe "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8.2.0  # Immutable
        with:
          projectBaseDir: contenttree-frontend
          args: >
            -Dsonar.projectVersion=${{ steps.get-frontend-version.outputs.version }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dependency-review:
    name: Dependency Review
    needs: [build-backend, build-frontend]
    if: ${{ (github.event_name == 'pull_request') && !cancelled() }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: (Harden Runner)
        uses: step-security/harden-runner@v2.19.4  # Immutable
        with:
          egress-policy: audit
          disable-telemetry: true

      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          fetch-depth: 0

      - name: Dependency Review
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294  # v5.0.0
        with:
          show-patched-versions: true
